language: node_js
sudo: true
node_js:
- '14.17.0'

script: npm run test:single

addons:
  chrome: stable

before_install:
    - # start your web application and listen on `localhost`
    - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
    ⋮


notifications:
  email: false

#cache:
#  directories:
#    - node_modules

after_success:
- npm run codecov


dist: xenial

