language: node_js
sudo: true
node_js:
- '8.11.1'

script: npm run test:single

addons:
  chrome: stable


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

notifications:
  email: false

#cache:
#  directories:
#    - node_modules

after_success:
- npm run codecov


dist: trusty